/**
 * The five steps, in one place.
 *
 * Both the landing-page section and `/process` read from here. They used to be
 * two copies of the same list, which is how a homepage ends up promising a
 * step the process page has renamed.
 *
 * `summary` is what the landing page shows. `body` and `deliverables` are the
 * expansion, and only `/process` renders them.
 */

export type Phase = {
  num: string;
  /** Anchor id — `/process#engineer` has to keep working. */
  slug: string;
  title: string;
  /** The one-liner. Shared with the landing page; changing it changes both. */
  summary: string;
  /** Expanded paragraph. `/process` only. */
  body: string;
  /** Three, not four. We do not have four honest ones per phase. */
  deliverables: string[];
  /** Generated by scripts/generate-process-art.js. */
  plate: string;
};

export const PHASES: Phase[] = [
  {
    num: "01",
    slug: "discover",
    title: "Discover",
    summary:
      "We learn your domain, your users, and your real constraints — before writing a single line of code.",
    body: "Most failed builds are failures of understanding, not of engineering. Before we estimate anything we sit with the people who will use the system and the people who will pay for it — usually not the same people — and write down what they actually need. Constraints get named here, while they are still cheap: the integration nobody mentioned, the compliance rule, the team that has to maintain this after we leave.",
    deliverables: [
      "A written problem statement both sides have agreed to",
      "A map of users, systems, and the constraints that bind them",
      "A scope we are willing to be held to",
    ],
    plate: "/images/process/phase-01-discover.png",
  },
  {
    num: "02",
    slug: "architect",
    title: "Architect",
    summary:
      "We design systems that solve today's problems without creating tomorrow's technical debt.",
    body: "Architecture is where cost is decided. We choose boring, well-understood technology by default and write down why — including what we rejected and what would change our mind. The design targets the load you have plus the growth you can defend, not a hypothetical scale that buys complexity you pay for in every sprint after.",
    deliverables: [
      "A system design covering data model, integrations, and failure modes",
      "A decision record — what we chose, what we rejected, and why",
      "A delivery plan broken into two-week sprints",
    ],
    plate: "/images/process/phase-02-architect.png",
  },
  {
    num: "03",
    slug: "engineer",
    title: "Engineer",
    summary:
      "Two-week sprints with working software every cycle. Full transparency, no black-box development.",
    body: "Every two weeks you get software you can open, not a status report. The work happens in the open — the board, the repository, and the staging environment are yours to look at whenever you want, not on a schedule we control. If something slips you hear about it in the sprint it slips in, not at the end.",
    deliverables: [
      "Working software deployed to staging at the end of every sprint",
      "Repository, board, and environment access from day one",
      "A sprint review where we demo rather than present",
    ],
    plate: "/images/process/phase-03-engineer.png",
  },
  {
    num: "04",
    slug: "qa-review",
    title: "QA & Review",
    summary:
      "Automated test coverage, peer code reviews, and performance audits before every release.",
    body: "Nothing ships on one person's judgement. Every change is read by someone who did not write it, covered by tests that run on every push, and measured against the performance and accessibility budget set at design time. A bug found here costs an hour. The same bug found by your users costs considerably more than that.",
    deliverables: [
      "An automated test suite running in CI on every change",
      "Peer review on every merge — no exceptions for urgency",
      "A pre-release audit: performance, accessibility, and security",
    ],
    plate: "/images/process/phase-04-qa-review.png",
  },
  {
    num: "05",
    slug: "scale-support",
    title: "Scale & Support",
    summary:
      "We stand by our work post-launch — monitoring, optimizing, and growing with your product.",
    body: "Launch is the middle of the project, not the end of it. Monitoring and alerting go in before the first real user arrives, so we find out about problems before you do. After that the arrangement is whatever fits — a retainer, a scheduled improvement cycle, or a clean handover to your own team with documentation that makes the handover real.",
    deliverables: [
      "Monitoring, alerting, and a runbook someone else can follow",
      "A post-launch review against the outcomes we agreed",
      "A support arrangement that matches how you actually work",
    ],
    plate: "/images/process/phase-05-scale-support.png",
  },
];

/**
 * How we work, as opposed to what we do. Each one is claimed somewhere else on
 * the site already — this is where they are collected, not where they are
 * invented.
 */
export const PRINCIPLES = [
  {
    title: "Working software, every two weeks",
    desc: "Progress you can open and click through, not a percentage in a status report.",
  },
  {
    title: "No black boxes",
    desc: "Repository, board, and environments are yours from day one. Nothing about the build is hidden from the people paying for it.",
  },
  {
    title: "Boring technology by default",
    desc: "We pick well-understood tools and write down why. Novelty has to earn its place against the cost of maintaining it.",
  },
  {
    title: "Bad news early",
    desc: "A slip you hear about in week two is a scheduling problem. The same slip at handover is a crisis.",
  },
  {
    title: "Reviewed by someone else",
    desc: "Every change is read by a second engineer before it merges. Urgency is not an exception to this.",
  },
  {
    title: "We stay after launch",
    desc: "Monitoring, optimisation, and support — or a documented handover clean enough that your team does not need us.",
  },
];
