import type { Metadata, Viewport } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

/** Display face per the identity hand-off. Variable (wght 300–700), so no
 *  `weight` — the axis covers the 500/700 the brand sets headlines at. */
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
});

/** Must match the deployed origin — og:image/canonical URLs resolve against this. */
const SITE_URL = "https://www.velquortech.com";
const SITE_NAME = "Velquor";
const SITE_DESCRIPTION =
  "Velquor builds production-grade web platforms, mobile apps, and backend systems for ambitious companies. Engineered to scale from day one.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Velquor — Software Development Studio",
    template: "%s — Velquor",
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "Velquor",
    "software development studio",
    "web development",
    "mobile app development",
    "React",
    "React Native",
    "Next.js",
    "backend systems",
    "product engineering",
    "Philippines software studio",
  ],
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  alternates: {
    canonical: "/",
  },
  // Icons come from the app/ file conventions — favicon.ico, icon.png and
  // apple-icon.png, all generated by scripts/generate-icons.js. Declaring them
  // here as well would emit duplicate <link> tags. The old apple entry pointed
  // at the transparent white mark, which iOS composites onto white.
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: "Velquor — Software Development Studio",
    description: SITE_DESCRIPTION,
    locale: "en_US",
    images: [
      {
        url: "/images/og-image.png",
        width: 1200,
        height: 630,
        alt: "Velquor — Software Development Studio",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Velquor — Software Development Studio",
    description: SITE_DESCRIPTION,
    images: ["/images/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

/** The brand is dark-only — tell the UA so form controls and scrollbars follow. */
export const viewport: Viewport = {
  themeColor: "#06000f",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${spaceGrotesk.variable} h-full`}
    >
      <body className="min-h-full bg-canvas text-ink antialiased">
        {/* Canvas texture is the body dot-grid (globals.css). The old fixed
            circuit-trace overlay lived here and was retired with the Framer
            study — the identity's texture is the dot field and StepField. */}
        <div className="relative" style={{ zIndex: 2 }}>
          {children}
        </div>
      </body>
    </html>
  );
}
